### ISSUE TITLE
本番環境で画像がダウンロードできない

### ISSUE THREAD

**Issue by shanbenkazuki** [shanbenkazuki/tier_atelier#110]
画像をダウンロードしようとするとエラーが発生する
```
エラーが発生しました: {"error":"Error: Executable doesn't exist at /app/.cache/ms-playwright/chromium-1080/chrome-linux/chrome\n╔════════════════════════════════════════════════════════════╗\n║ Looks like Playwright was just installed or updated.       ║\n║ Please run the following command to download new browsers: ║\n║                                                            ║\n║     playwright install                                     ║\n║                                                            ║\n║ \u003c3 Playwright Team                                         ║\n╚════════════════════════════════════════════════════════════╝","backtrace":["/app/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/promises.rb:1258:in `raise'","/app/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/promises.rb:1258:in `wait_until_resolved!'","/app/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/promises.rb:1472:in `value!'","/app/vendor/bundle/ruby/3.2.0/gems/playwright-ruby-client-1.37.1/lib/playwright/connection.rb:104:in `send_message_to_server'","/app/vendor/bundle/ruby/3.2.0/gems/playwright-ruby-client-1.37.1/lib/playwright/channel.rb:34:in `block in send_message_to_server_result'","/app/vendor/bundle/ruby/3.2.0/gems/playwright-ruby-client-1.37.1/lib/playwright/channel.rb:65:in `with_logging'","/app/vendor/bundle/ruby/3.2.0/gems/playwright-ruby-client-1.37.1/lib/playwright/channel.rb:33:in `send_message_to_server_result'","/app/vendor/bundle/ruby/3.2.0/gems/playwright-ruby-client-1.37.1/lib/playwright/channel.rb:20:in `send_message_to_server'","/app/vendor/bundle/ruby/3.2.0/gems/playwright-ruby-...

```

**Comment by shanbenkazuki** [comment]
devDependencies は、開発時やテスト時にのみ必要とされる依存関係のようなので、dependenciesに移しても変化なし

**Comment by shanbenkazuki** [comment]
Node.js ビルドパックの追加
https://zenn.dev/junki555/articles/400589974d3034
上記を参考にnodeを入れても変化なし

**Comment by shanbenkazuki** [comment]
そもそもテスト用だということもあるので、htmltocanvasで動かせるように修正する
