### ISSUE TITLE
画像の位置を更新したあと画面更新をするとエラーになる

### ISSUE THREAD

**Issue by shanbenkazuki** [shanbenkazuki/tier_atelier#122]
### As Is
画像を動かしてから画面を更新するとInvariableErrorになる

### To Be 
エラー解消

### アクション
（改善のための具体的なアクションを記載）

### 課題
（現状分かっている課題を記載）

**Comment by shanbenkazuki** [comment]
全文
```
ArgumentError: wrong number of arguments (given 0, expected 1)
from /Users/yamamotokazuki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activestorage-7.0.6/app/models/active_storage/attachment.rb:56:in `variant'
[4] pry(#<TiersController>)> item.image.variant(resize_to_limit: [50, nil])
NameError: Rails couldn't find a valid model for ActiveStorage::Blob association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass.
from /Users/yamamotokazuki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.6/lib/active_record/reflection.rb:441:in `rescue in compute_class'
Caused by NameError: uninitialized constant ActiveStorage::Blob::Analyzable
from /Users/yamamotokazuki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activestorage-7.0.6/app/models/active_storage/blob.rb:33:in `<class:Blob>'
```

**Comment by shanbenkazuki** [comment]
マイグレーション再インストールをとりあえずしてみる

ID確認
```
bundle exec rails db:migrate:status
```

down
```
bundle exec rails db:migrate:down VERSION=20230803043601
```

**Comment by shanbenkazuki** [comment]
更新するときにエラーが起きてる。
active_storageに保存されている値が想定と違う。
このあたりが原因のよう

**Comment by shanbenkazuki** [comment]
そもそも位置を更新するときに、画像の情報については触らないように修正した
