### ISSUE TITLE
本番エラー（メール設定？）

### ISSUE THREAD

**Issue by shanbenkazuki** [shanbenkazuki/tier_atelier#17]
kazuki@MacBook-Pro-2 tier_atelier % heroku logs --tail
2023-07-25T04:54:30.681110+00:00 app[web.1]: from /app/bin/bundle:108:in `load'
2023-07-25T04:54:30.681110+00:00 app[web.1]: from /app/bin/bundle:108:in `<main>'
2023-07-25T04:54:30.821102+00:00 heroku[web.1]: Process exited with status 1
2023-07-25T04:54:30.850858+00:00 heroku[web.1]: State changed from starting to crashed
2023-07-25T04:54:30.854151+00:00 heroku[web.1]: State changed from crashed to starting
2023-07-25T04:54:33.909405+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2023-07-25T04:54:35.283508+00:00 app[web.1]: Puma starting in single mode...
2023-07-25T04:54:35.283547+00:00 app[web.1]: * Puma version: 5.6.6 (ruby 3.2.2-p53) ("Birdie's Version")
2023-07-25T04:54:35.283551+00:00 app[web.1]: *  Min threads: 5
2023-07-25T04:54:35.283551+00:00 app[web.1]: *  Max threads: 5
2023-07-25T04:54:35.283551+00:00 app[web.1]: *  Environment: production
2023-07-25T04:54:35.283551+00:00 app[web.1]: *          PID: 2
2023-07-25T04:54:37.068719+00:00 app[web.1]: ! Unable to load application: ArgumentError: To use reset_password submodule, you must define a mailer (config.reset_password_mailer = YourMailerClass).
2023-07-25T04:54:37.068874+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/3.2.0/bin/puma)
2023-07-25T04:54:37.069967+00:00 app[web.1]: /app/vendor/bundle/ruby/3.2.0/gems/sorcery-0.16.5/lib/sorcery/model/submodules/reset_password.rb:77:in `validate_mailer_defined': To use reset_password submodule, you must define a mailer (config.reset_password_mailer = YourMailerClass). (ArgumentError)
2023-07-25T04:54:37.069968+00:00 app[web.1]: 
2023-07-25T04:54:37.069968+00:00 app[web.1]: raise ArgumentError, message if @sorcery_config.reset_password_mailer.nil? && @sorcery_config.reset_password_mailer_disabled == false
2023-07-25T04:54:37.069968+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^
2023-07-25T04:54:37.069973+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/sorcery-0.16.5/lib/sorcery/model.rb:26:in `block in authenticates_with_sorcery!'
2023-07-25T04:54:37.069973+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/sorcery-0.16.5/lib/sorcery/model.rb:26:in `each'
2023-07-25T04:54:37.069974+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/sorcery-0.16.5/lib/sorcery/model.rb:26:in `authenticates_with_sorcery!'
2023-07-25T04:54:37.069976+00:00 app[web.1]: from /app/app/models/user.rb:2:in `<class:User>'
2023-07-25T04:54:37.069976+00:00 app[web.1]: from /app/app/models/user.rb:1:in `<main>'
2023-07-25T04:54:37.069977+00:00 app[web.1]: from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-07-25T04:54:37.069978+00:00 app[web.1]: from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-07-25T04:54:37.069979+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2023-07-25T04:54:37.069980+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
2023-07-25T04:54:37.069980+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
2023-07-25T04:54:37.069980+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:135:in `cget'
2023-07-25T04:54:37.069980+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
2023-07-25T04:54:37.069980+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
2023-07-25T04:54:37.069981+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:25:in `each'
2023-07-25T04:54:37.069981+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:25:in `ls'
2023-07-25T04:54:37.069981+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
2023-07-25T04:54:37.069982+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
2023-07-25T04:54:37.069982+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:16:in `each'
2023-07-25T04:54:37.069982+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
2023-07-25T04:54:37.069982+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
2023-07-25T04:54:37.069982+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
2023-07-25T04:54:37.069982+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:329:in `block in eager_load_all'
2023-07-25T04:54:37.069982+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:327:in `each'
2023-07-25T04:54:37.069983+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:327:in `eager_load_all'
2023-07-25T04:54:37.069983+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
2023-07-25T04:54:37.069983+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `instance_exec'
2023-07-25T04:54:37.069983+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `run'
2023-07-25T04:54:37.069983+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:61:in `block in run_initializers'
2023-07-25T04:54:37.069983+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
2023-07-25T04:54:37.069984+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2023-07-25T04:54:37.069984+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
2023-07-25T04:54:37.069984+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
2023-07-25T04:54:37.069984+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
2023-07-25T04:54:37.069984+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
2023-07-25T04:54:37.069984+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
2023-07-25T04:54:37.069985+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
2023-07-25T04:54:37.069987+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
2023-07-25T04:54:37.069987+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/initializable.rb:60:in `run_initializers'
2023-07-25T04:54:37.069988+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/application.rb:372:in `initialize!'
2023-07-25T04:54:37.069988+00:00 app[web.1]: from /app/config/environment.rb:5:in `<top (required)>'
2023-07-25T04:54:37.069988+00:00 app[web.1]: from config.ru:3:in `require_relative'
2023-07-25T04:54:37.069988+00:00 app[web.1]: from config.ru:3:in `block in <main>'
2023-07-25T04:54:37.069989+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
2023-07-25T04:54:37.069989+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
2023-07-25T04:54:37.069989+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
2023-07-25T04:54:37.069989+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
2023-07-25T04:54:37.069989+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.6/lib/puma/configuration.rb:348:in `load_rackup'
2023-07-25T04:54:37.069990+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.6/lib/puma/configuration.rb:270:in `app'
2023-07-25T04:54:37.069990+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.6/lib/puma/runner.rb:150:in `load_and_bind'
2023-07-25T04:54:37.069990+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.6/lib/puma/single.rb:44:in `run'
2023-07-25T04:54:37.069990+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.6/lib/puma/launcher.rb:193:in `run'
2023-07-25T04:54:37.069990+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.6/lib/puma/cli.rb:81:in `run'
2023-07-25T04:54:37.069990+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.6/bin/puma:10:in `<top (required)>'
2023-07-25T04:54:37.069991+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/bin/puma:25:in `load'
2023-07-25T04:54:37.069991+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/bin/puma:25:in `<top (required)>'
2023-07-25T04:54:37.069991+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
2023-07-25T04:54:37.069991+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
2023-07-25T04:54:37.069991+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
2023-07-25T04:54:37.069992+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
2023-07-25T04:54:37.069992+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2023-07-25T04:54:37.069992+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
2023-07-25T04:54:37.069992+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
2023-07-25T04:54:37.069992+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
2023-07-25T04:54:37.069993+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
2023-07-25T04:54:37.069993+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
2023-07-25T04:54:37.069993+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
2023-07-25T04:54:37.069993+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
2023-07-25T04:54:37.069993+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
2023-07-25T04:54:37.069993+00:00 app[web.1]: from /app/bin/bundle:108:in `load'
2023-07-25T04:54:37.069993+00:00 app[web.1]: from /app/bin/bundle:108:in `<main>'
2023-07-25T04:54:37.244342+00:00 heroku[web.1]: Process exited with status 1
2023-07-25T04:54:37.273199+00:00 heroku[web.1]: State changed from starting to crashed
2023-07-25T04:54:47.684404+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secure-wave-69398-dd6dfea6aac7.herokuapp.com request_id=f8bb7bea-68d7-4305-8776-79f2a71479a1 fwd="118.241.60.96" dyno= connect= service= status=503 bytes= protocol=https
2023-07-25T04:54:48.324717+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secure-wave-69398-dd6dfea6aac7.herokuapp.com request_id=7e062ce3-08d3-4670-8f0a-aa14ab15b73c fwd="118.241.60.96" dyno= connect= service= status=503 bytes= protocol=https
2023-07-25T04:55:34.091408+00:00 app[api]: Starting process with command `bundle exec rake db:migrate` by user shanbenkazuki15@gmail.com
2023-07-25T04:55:37.617630+00:00 heroku[run.4003]: Awaiting client
2023-07-25T04:55:37.632682+00:00 heroku[run.4003]: Starting process with command `bundle exec rake db:migrate`
2023-07-25T04:55:37.729812+00:00 heroku[run.4003]: State changed from starting to up
2023-07-25T04:55:43.267006+00:00 heroku[run.4003]: Process exited with status 0
2023-07-25T04:55:43.295842+00:00 heroku[run.4003]: State changed from up to complete
2023-07-25T04:55:54.135500+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=secure-wave-69398-dd6dfea6aac7.herokuapp.com request_id=8907e41a-b323-474e-81e5-4b80b75b1db0 fwd="118.241.60.96" dyno= connect= service= status=503 bytes= protocol=https
2023-07-25T04:55:54.722154+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=secure-wave-69398-dd6dfea6aac7.herokuapp.com request_id=0657a1a0-7ce8-4b7d-b25c-84a59431141c fwd="118.241.60.96" dyno= connect= service= status=503 bytes= protocol=https

**Comment by shanbenkazuki** [comment]
resetpasswordの設定してないのが原因のエラー
https://github.com/Sorcery/sorcery/wiki/Reset-password

**Comment by shanbenkazuki** [comment]
resetpasswordを設定しようとすると、ログイン周りを作らないといけなくなるので、テーブルにresetpasswordに関連するカラムを消して後回しにする

**Comment by shanbenkazuki** [comment]
対処として、テーブルのresetpasswordに関連するカラムを消す

**Comment by shanbenkazuki** [comment]
bin/rails generate sorcery:install reset_password

**Comment by shanbenkazuki** [comment]
userテーブル作成時に、resetpasswordを削除

もちろんです、`bin/rails`コマンドを使ってマイグレーションを生成するには以下のコマンドを実行します：

1. **Categories テーブル:**

```bash
bin/rails generate model Category name:string cover_image_url:string
```

2. **Users テーブル:**
soerceryコマンドから作成
```
bin/rails generate sorcery:install
```


3. **Relationship テーブル:**

```bash
bin/rails g model Relationship follower_id:integer followed_id:integer
```

4. **Templates テーブル:**

```bash
bin/rails generate model Template user:references title:string description:text cover_image_url:string category:references
```

5. **TemplateItems テーブル:**

```bash
bin/rails generate model TemplateItem template:references name:string image_url:string order:integer
```

6. **TierLists テーブル:**

```bash
bin/rails generate model TierList user:references title:string description:text category:references
```

7. **Tiers テーブル:**

```bash
bin/rails generate model Tier tier_list:references horizontal_name:string vertical_name:string horizontal_order:integer vertical_order:integer
```

8. **Items テーブル:**

```bash
bin/rails generate model Item tier_list:references name:string image_url:string order:integer
```

9. **Comments テーブル:**

```bash
bin/rails generate model Comment user:references tier_list:references body:text
```

10. **Likes テーブル:**

```bash
bin/rails generate model Like user:references tier_list:references
```

それぞれのマイグレーションファイルが生成された後で、データベースにマイグレーションを適用します：

```bash
bin/rails db:migrate
```

これで、各テーブルが作成され、外部キー制約によるエラーは発生しなくなります。

ただし、Relationshipテーブルのような自己参照関係のテーブルを作る際には、追加の設定が必要になります。生成されたマイグレーションファイル内で、`follower_id`と`following_id`が共に`Users`テーブルを参照するように設定し、同様にモデルファイル内で適切な関連付けを設定する必要があります。

**Comment by shanbenkazuki** [comment]
本番のdbがコマンドでresetできないので、アプリを削除して再度初めからデプロイ

**Comment by shanbenkazuki** [comment]
done
